.nh
.TH "TAKO" "1" "Jun 2026" "Tako CLI" "Tako CLI Manual"

.SH NAME
tako-secrets - Manage deployment secrets


.SH SYNOPSIS
\fBtako secrets [flags]\fP


.SH DESCRIPTION
Manage secrets stored in .tako/secrets files. Secrets are stored locally and never committed to git.


.SH OPTIONS
\fB-h\fP, \fB--help\fP[=false]
	help for secrets


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is ./tako.yaml or ./tako.json)

.PP
\fB-e\fP, \fB--env\fP=""
	environment to deploy (default: production or only environment)

.PP
\fB--events\fP=""
	stream progress events to stdout: ndjson (human output moves to stderr)

.PP
\fB--host-key-mode\fP=""
	SSH host key verification mode: tofu, strict, ask (default: tofu)

.PP
\fB--output\fP="text"
	output format: text or json (json reserves stdout for the final result document)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBtako(1)\fP, \fBtako-secrets-delete(1)\fP, \fBtako-secrets-fetch(1)\fP, \fBtako-secrets-import(1)\fP, \fBtako-secrets-init(1)\fP, \fBtako-secrets-list(1)\fP, \fBtako-secrets-set(1)\fP, \fBtako-secrets-validate(1)\fP
