.nh
.TH "TAKO" "1" "Jun 2026" "Tako CLI" "Tako CLI Manual"

.SH NAME
tako-placement-plan-cordon - Plan the replica impact of excluding one node from new placement


.SH SYNOPSIS
\fBtako placement plan cordon [flags]\fP


.SH DESCRIPTION
Plan the replica impact of excluding one node from new placement


.SH OPTIONS
\fB--file\fP=""
	Write the reviewable plan JSON atomically

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for cordon

.PP
\fB--node\fP=""
	Logical node name or immutable node UUID (required)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is ./tako.yaml or ./tako.json)

.PP
\fB-e\fP, \fB--env\fP=""
	environment to deploy (default: production or only environment)

.PP
\fB--events\fP=""
	stream progress events to stdout: ndjson (human output moves to stderr)

.PP
\fB--host-key-mode\fP=""
	SSH host key verification mode: tofu, strict, ask (default: tofu)

.PP
\fB--output\fP="text"
	output format: text or json (json reserves stdout for the final result document)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBtako-placement-plan(1)\fP
