.nh
.TH "TAKO" "1" "Jun 2026" "Tako CLI" "Tako CLI Manual"

.SH NAME
tako-run - Deploy a public image to an existing takod node without tako.yaml


.SH SYNOPSIS
\fBtako run IMAGE [flags]\fP


.SH DESCRIPTION
Deploy a public image to an existing takod node without tako.yaml


.SH OPTIONS
\fB--domain\fP=""
	Public domain to route to the service

.PP
\fB--env\fP=[]
	Environment variable KEY=VALUE (repeatable)

.PP
\fB--environment\fP="production"
	Environment name

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for run

.PP
\fB--name\fP=""
	Project and service name (required)

.PP
\fB--password\fP=""
	SSH password

.PP
\fB--port\fP=0
	Container port to expose (required)

.PP
\fB--replicas\fP=1
	Number of replicas

.PP
\fB--server\fP=""
	SSH host for the remote takod node (required)

.PP
\fB--server-name\fP=""
	Generated config server name (defaults to sanitized --server)

.PP
\fB--ssh-key\fP="~/.ssh/id_rsa"
	SSH private key path

.PP
\fB--ssh-port\fP=22
	SSH port

.PP
\fB--user\fP=""
	SSH user (defaults to current user)

.PP
\fB-y\fP, \fB--yes\fP[=false]
	Skip confirmation prompts (non-interactive mode)


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is ./tako.yaml or ./tako.json)

.PP
\fB--host-key-mode\fP=""
	SSH host key verification mode: tofu, strict, ask (default: tofu)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBtako(1)\fP
