.nh
.TH "TAKO" "1" "Jun 2026" "Tako CLI" "Tako CLI Manual"

.SH NAME
tako-secrets-list - List all secret keys


.SH SYNOPSIS
\fBtako secrets list [flags]\fP


.SH DESCRIPTION
List all secret keys (values are redacted for security).


.SH OPTIONS
\fB-e\fP, \fB--env\fP=""
	Environment (e.g., production, staging)

.PP
\fB-h\fP, \fB--help\fP[=false]
	help for list


.SH OPTIONS INHERITED FROM PARENT COMMANDS
\fB--config\fP=""
	config file (default is ./tako.yaml or ./tako.json)

.PP
\fB--host-key-mode\fP=""
	SSH host key verification mode: tofu, strict, ask (default: tofu)

.PP
\fB-v\fP, \fB--verbose\fP[=false]
	verbose output


.SH SEE ALSO
\fBtako-secrets(1)\fP
