package cmd

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"
)

func TestTrackedCompletionsMatchGeneratedOutput(t *testing.T) {
	tests := []struct {
		name     string
		file     string
		generate func(*bytes.Buffer) error
	}{
		{
			name: "bash",
			file: "tako.bash",
			generate: func(out *bytes.Buffer) error {
				return rootCmd.GenBashCompletionV2(out, true)
			},
		},
		{
			name: "zsh",
			file: "tako.zsh",
			generate: func(out *bytes.Buffer) error {
				return rootCmd.GenZshCompletion(out)
			},
		},
		{
			name: "fish",
			file: "tako.fish",
			generate: func(out *bytes.Buffer) error {
				return rootCmd.GenFishCompletion(out, true)
			},
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var generated bytes.Buffer
			if err := tt.generate(&generated); err != nil {
				t.Fatalf("failed to generate %s completions: %v", tt.name, err)
			}

			path := filepath.Join("..", "completions", tt.file)
			tracked, err := os.ReadFile(path)
			if err != nil {
				t.Fatalf("failed to read tracked %s completions: %v", tt.name, err)
			}
			if string(tracked) != generated.String() {
				t.Fatalf("%s completions are stale; regenerate with `tako completion %s > completions/%s`", tt.name, tt.name, tt.file)
			}
		})
	}
}
